version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-ddd
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ddd-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - ddd-network

  springboot:
    build: .
    container_name: springboot-ddd
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      SERVER_PORT: ${SPRING_PORT}
      CONTEXT_PATH: ${CONTEXT_PATH}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
      LOG_LEVEL: ${LOG_LEVEL}
      APP_LOG_LEVEL: ${APP_LOG_LEVEL}
      UPLOAD_DIR: ${UPLOAD_DIR}
      MAX_FILE_SIZE: ${MAX_FILE_SIZE}
      TIMEZONE: ${TIMEZONE}
    ports:
      - "8081:8080" # Externo:Interno
    depends_on:
      - postgres
    networks:
      - ddd-network

volumes:
  ddd-data:

networks:
  ddd-network:
    driver: bridge